name: Release Verifcation

on:
  workflow_dispatch:

jobs:
  release-verify:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    strategy:
      fail-fast: false
      matrix:
        duckdb_version: ['0.8.0', '0.8.1']
        python_version: ['3.8', '3.9', '3.10', '3.11']
        arch: ['linux_amd64']
    env:
      PYTHON_VERSION: ${{ matrix.python_version }}
      DUCKDB_VERSION: ${{ matrix.duckdb_version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        - name: Integration Tests
          run: |
            make RELEASE_SHA=latest post-release-integration

        - name: Installer Tests
          run: |
            make GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} test-installer
                                                                            
